language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t randydavis/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true randydavis/docker-react npm run test