version: '3'
services:
    web:
        build: 
            context: . # Specifies where we want all files and folders to be pulled from
            dockerfile: Dockerfile.dev # Name of dockerfile to be used to build and run container
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
    #tests:
    #    build:
    #        context: .
    #        dockerfile: Dockerfile.dev
    #    volumes: 
    #        - /app/node_modules
    #        - .:/app
    #    command: [ "npm", "run", "test" ] # Override our default "npm run start" starting command to use this instead